FROM node:18-alpine

WORKDIR /app

# Bağımlılıkları kopyala ve yükle
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Uygulama dosyalarını kopyala
COPY . .

# Tailwind CSS'i derle ve Next.js uygulamasını build et
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]